version: '3'

services:
  front_end:
    image: "node:alpine"
    build: ./services/front_end
    working_dir: /home/node/app
    volumes:
     - ${PWD}/volumes/front_end:/home/node/app:rw
    ports:
     - "3000:3000"
    environment:
      APP_MOUNT_ID: ${APP_MOUNT_ID}
    command: "npm run ${NPM_SCRIPT}"
